//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/controller input system/MenuUI Control.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MenuUIControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MenuUIControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MenuUI Control"",
    ""maps"": [
        {
            ""name"": ""ui control"",
            ""id"": ""8ce71ca8-2a88-4ff1-b3f6-21148e7d4797"",
            ""actions"": [
                {
                    ""name"": ""left"",
                    ""type"": ""Button"",
                    ""id"": ""a890c381-c6a3-437d-bd39-954339f8d93b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""right"",
                    ""type"": ""Button"",
                    ""id"": ""a64064d1-e2bb-4131-9339-4ab174b8e4b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""selectLevel"",
                    ""type"": ""Button"",
                    ""id"": ""caf3701e-d9a4-4f3c-af6b-3479ba2e1a70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cdf6aefe-8659-46e0-a31f-f283643a678f"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc98fc56-5bc5-448f-8bfa-f2e185a2c3ff"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61bd54b9-b048-4ec1-899a-c1a52dc3ce5a"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e737e4e8-48e3-4b48-a11f-c7814f9d43d7"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03bd145c-19cd-4f6c-96d7-f9d102695057"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""selectLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""startSceneControl"",
            ""id"": ""30e0cb56-17d7-4b07-86a2-88443125b8d1"",
            ""actions"": [
                {
                    ""name"": ""anybutton"",
                    ""type"": ""Button"",
                    ""id"": ""b97c4bd7-01c2-489c-a5f1-e4de64790e39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""39f98c0d-5f08-40c1-8cfc-76bad0fb0a97"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""anybutton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41282ad3-406a-47b8-8fad-a52cfb4d6d50"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""anybutton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1491cbc6-ac9d-4eab-96c2-a10848daf59e"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""anybutton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71ebd46c-b987-4ece-8665-22c2bc215b9c"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""anybutton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5b40fa5-e1de-4279-9325-e44e35dc33c2"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""anybutton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86e976ff-30e1-4627-a482-9920cae804d4"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""anybutton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a02af0f9-009d-42cd-9794-3b4bc7d91f0f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""anybutton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e36ed29-2b60-4ffb-b74f-256faceafc9a"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""anybutton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35fc98b6-7189-44a3-b2da-00cebb7e5c36"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""anybutton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b93f875-5a3e-4c35-8d4d-550f3fa8a511"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""anybutton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0df072e-8dc1-4569-a2c8-4970af43c41e"",
                    ""path"": ""<DualShockGamepad>/touchpadButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""anybutton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ui control
        m_uicontrol = asset.FindActionMap("ui control", throwIfNotFound: true);
        m_uicontrol_left = m_uicontrol.FindAction("left", throwIfNotFound: true);
        m_uicontrol_right = m_uicontrol.FindAction("right", throwIfNotFound: true);
        m_uicontrol_selectLevel = m_uicontrol.FindAction("selectLevel", throwIfNotFound: true);
        // startSceneControl
        m_startSceneControl = asset.FindActionMap("startSceneControl", throwIfNotFound: true);
        m_startSceneControl_anybutton = m_startSceneControl.FindAction("anybutton", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ui control
    private readonly InputActionMap m_uicontrol;
    private List<IUicontrolActions> m_UicontrolActionsCallbackInterfaces = new List<IUicontrolActions>();
    private readonly InputAction m_uicontrol_left;
    private readonly InputAction m_uicontrol_right;
    private readonly InputAction m_uicontrol_selectLevel;
    public struct UicontrolActions
    {
        private @MenuUIControl m_Wrapper;
        public UicontrolActions(@MenuUIControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @left => m_Wrapper.m_uicontrol_left;
        public InputAction @right => m_Wrapper.m_uicontrol_right;
        public InputAction @selectLevel => m_Wrapper.m_uicontrol_selectLevel;
        public InputActionMap Get() { return m_Wrapper.m_uicontrol; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UicontrolActions set) { return set.Get(); }
        public void AddCallbacks(IUicontrolActions instance)
        {
            if (instance == null || m_Wrapper.m_UicontrolActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UicontrolActionsCallbackInterfaces.Add(instance);
            @left.started += instance.OnLeft;
            @left.performed += instance.OnLeft;
            @left.canceled += instance.OnLeft;
            @right.started += instance.OnRight;
            @right.performed += instance.OnRight;
            @right.canceled += instance.OnRight;
            @selectLevel.started += instance.OnSelectLevel;
            @selectLevel.performed += instance.OnSelectLevel;
            @selectLevel.canceled += instance.OnSelectLevel;
        }

        private void UnregisterCallbacks(IUicontrolActions instance)
        {
            @left.started -= instance.OnLeft;
            @left.performed -= instance.OnLeft;
            @left.canceled -= instance.OnLeft;
            @right.started -= instance.OnRight;
            @right.performed -= instance.OnRight;
            @right.canceled -= instance.OnRight;
            @selectLevel.started -= instance.OnSelectLevel;
            @selectLevel.performed -= instance.OnSelectLevel;
            @selectLevel.canceled -= instance.OnSelectLevel;
        }

        public void RemoveCallbacks(IUicontrolActions instance)
        {
            if (m_Wrapper.m_UicontrolActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUicontrolActions instance)
        {
            foreach (var item in m_Wrapper.m_UicontrolActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UicontrolActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UicontrolActions @uicontrol => new UicontrolActions(this);

    // startSceneControl
    private readonly InputActionMap m_startSceneControl;
    private List<IStartSceneControlActions> m_StartSceneControlActionsCallbackInterfaces = new List<IStartSceneControlActions>();
    private readonly InputAction m_startSceneControl_anybutton;
    public struct StartSceneControlActions
    {
        private @MenuUIControl m_Wrapper;
        public StartSceneControlActions(@MenuUIControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @anybutton => m_Wrapper.m_startSceneControl_anybutton;
        public InputActionMap Get() { return m_Wrapper.m_startSceneControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StartSceneControlActions set) { return set.Get(); }
        public void AddCallbacks(IStartSceneControlActions instance)
        {
            if (instance == null || m_Wrapper.m_StartSceneControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_StartSceneControlActionsCallbackInterfaces.Add(instance);
            @anybutton.started += instance.OnAnybutton;
            @anybutton.performed += instance.OnAnybutton;
            @anybutton.canceled += instance.OnAnybutton;
        }

        private void UnregisterCallbacks(IStartSceneControlActions instance)
        {
            @anybutton.started -= instance.OnAnybutton;
            @anybutton.performed -= instance.OnAnybutton;
            @anybutton.canceled -= instance.OnAnybutton;
        }

        public void RemoveCallbacks(IStartSceneControlActions instance)
        {
            if (m_Wrapper.m_StartSceneControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IStartSceneControlActions instance)
        {
            foreach (var item in m_Wrapper.m_StartSceneControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_StartSceneControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public StartSceneControlActions @startSceneControl => new StartSceneControlActions(this);
    public interface IUicontrolActions
    {
        void OnLeft(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnSelectLevel(InputAction.CallbackContext context);
    }
    public interface IStartSceneControlActions
    {
        void OnAnybutton(InputAction.CallbackContext context);
    }
}
