//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/controller input system/playerControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/controller input system/playerControl.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerControl: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""playerControl"",
    ""maps"": [
        {
            ""name"": ""inGameControl"",
            ""id"": ""a7b7fb76-47fa-4561-a2a5-f1023351948c"",
            ""actions"": [
                {
                    ""name"": ""stickMovement"",
                    ""type"": ""Value"",
                    ""id"": ""b6ed247e-cb2d-4b0a-b20f-648dec7d3af2"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerHeadThrowAim"",
                    ""type"": ""Button"",
                    ""id"": ""9450f86f-f5ec-4d4a-88c7-47e4ec359ab1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerRebuild"",
                    ""type"": ""Button"",
                    ""id"": ""8cd5291b-35ae-4834-86b6-bc794d3eec4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""aimHead"",
                    ""type"": ""Value"",
                    ""id"": ""8c7c536a-5e77-4e9b-905a-5f61adc3f8d4"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""jump/cling"",
                    ""type"": ""Button"",
                    ""id"": ""89fea38b-2b29-4e62-8049-d0765679796d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerHeadThrow"",
                    ""type"": ""Button"",
                    ""id"": ""736b8ae8-a927-4a38-9abe-ed8af1889ff2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""52f35105-fe8a-4b38-8880-6bc13b9d7f89"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""stickMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4be54c7f-d7e5-4572-9089-24d485889161"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerHeadThrowAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31c617f8-9e9d-46fc-9991-54b9cadd73cb"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerRebuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46ee7940-39aa-46cd-b314-7d0491bf0231"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""aimHead"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da2fb662-db55-4706-b5fa-8b31ed3902e4"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump/cling"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9c3d6c2-1843-4af5-98dc-8e36513cbb33"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerHeadThrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // inGameControl
        m_inGameControl = asset.FindActionMap("inGameControl", throwIfNotFound: true);
        m_inGameControl_stickMovement = m_inGameControl.FindAction("stickMovement", throwIfNotFound: true);
        m_inGameControl_TriggerHeadThrowAim = m_inGameControl.FindAction("TriggerHeadThrowAim", throwIfNotFound: true);
        m_inGameControl_TriggerRebuild = m_inGameControl.FindAction("TriggerRebuild", throwIfNotFound: true);
        m_inGameControl_aimHead = m_inGameControl.FindAction("aimHead", throwIfNotFound: true);
        m_inGameControl_jumpcling = m_inGameControl.FindAction("jump/cling", throwIfNotFound: true);
        m_inGameControl_TriggerHeadThrow = m_inGameControl.FindAction("TriggerHeadThrow", throwIfNotFound: true);
    }

    ~@PlayerControl()
    {
        UnityEngine.Debug.Assert(!m_inGameControl.enabled, "This will cause a leak and performance issues, PlayerControl.inGameControl.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // inGameControl
    private readonly InputActionMap m_inGameControl;
    private List<IInGameControlActions> m_InGameControlActionsCallbackInterfaces = new List<IInGameControlActions>();
    private readonly InputAction m_inGameControl_stickMovement;
    private readonly InputAction m_inGameControl_TriggerHeadThrowAim;
    private readonly InputAction m_inGameControl_TriggerRebuild;
    private readonly InputAction m_inGameControl_aimHead;
    private readonly InputAction m_inGameControl_jumpcling;
    private readonly InputAction m_inGameControl_TriggerHeadThrow;
    /// <summary>
    /// Provides access to input actions defined in input action map "inGameControl".
    /// </summary>
    public struct InGameControlActions
    {
        private @PlayerControl m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public InGameControlActions(@PlayerControl wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "inGameControl/stickMovement".
        /// </summary>
        public InputAction @stickMovement => m_Wrapper.m_inGameControl_stickMovement;
        /// <summary>
        /// Provides access to the underlying input action "inGameControl/TriggerHeadThrowAim".
        /// </summary>
        public InputAction @TriggerHeadThrowAim => m_Wrapper.m_inGameControl_TriggerHeadThrowAim;
        /// <summary>
        /// Provides access to the underlying input action "inGameControl/TriggerRebuild".
        /// </summary>
        public InputAction @TriggerRebuild => m_Wrapper.m_inGameControl_TriggerRebuild;
        /// <summary>
        /// Provides access to the underlying input action "inGameControl/aimHead".
        /// </summary>
        public InputAction @aimHead => m_Wrapper.m_inGameControl_aimHead;
        /// <summary>
        /// Provides access to the underlying input action "inGameControl/jumpcling".
        /// </summary>
        public InputAction @jumpcling => m_Wrapper.m_inGameControl_jumpcling;
        /// <summary>
        /// Provides access to the underlying input action "inGameControl/TriggerHeadThrow".
        /// </summary>
        public InputAction @TriggerHeadThrow => m_Wrapper.m_inGameControl_TriggerHeadThrow;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_inGameControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="InGameControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(InGameControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="InGameControlActions" />
        public void AddCallbacks(IInGameControlActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameControlActionsCallbackInterfaces.Add(instance);
            @stickMovement.started += instance.OnStickMovement;
            @stickMovement.performed += instance.OnStickMovement;
            @stickMovement.canceled += instance.OnStickMovement;
            @TriggerHeadThrowAim.started += instance.OnTriggerHeadThrowAim;
            @TriggerHeadThrowAim.performed += instance.OnTriggerHeadThrowAim;
            @TriggerHeadThrowAim.canceled += instance.OnTriggerHeadThrowAim;
            @TriggerRebuild.started += instance.OnTriggerRebuild;
            @TriggerRebuild.performed += instance.OnTriggerRebuild;
            @TriggerRebuild.canceled += instance.OnTriggerRebuild;
            @aimHead.started += instance.OnAimHead;
            @aimHead.performed += instance.OnAimHead;
            @aimHead.canceled += instance.OnAimHead;
            @jumpcling.started += instance.OnJumpcling;
            @jumpcling.performed += instance.OnJumpcling;
            @jumpcling.canceled += instance.OnJumpcling;
            @TriggerHeadThrow.started += instance.OnTriggerHeadThrow;
            @TriggerHeadThrow.performed += instance.OnTriggerHeadThrow;
            @TriggerHeadThrow.canceled += instance.OnTriggerHeadThrow;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="InGameControlActions" />
        private void UnregisterCallbacks(IInGameControlActions instance)
        {
            @stickMovement.started -= instance.OnStickMovement;
            @stickMovement.performed -= instance.OnStickMovement;
            @stickMovement.canceled -= instance.OnStickMovement;
            @TriggerHeadThrowAim.started -= instance.OnTriggerHeadThrowAim;
            @TriggerHeadThrowAim.performed -= instance.OnTriggerHeadThrowAim;
            @TriggerHeadThrowAim.canceled -= instance.OnTriggerHeadThrowAim;
            @TriggerRebuild.started -= instance.OnTriggerRebuild;
            @TriggerRebuild.performed -= instance.OnTriggerRebuild;
            @TriggerRebuild.canceled -= instance.OnTriggerRebuild;
            @aimHead.started -= instance.OnAimHead;
            @aimHead.performed -= instance.OnAimHead;
            @aimHead.canceled -= instance.OnAimHead;
            @jumpcling.started -= instance.OnJumpcling;
            @jumpcling.performed -= instance.OnJumpcling;
            @jumpcling.canceled -= instance.OnJumpcling;
            @TriggerHeadThrow.started -= instance.OnTriggerHeadThrow;
            @TriggerHeadThrow.performed -= instance.OnTriggerHeadThrow;
            @TriggerHeadThrow.canceled -= instance.OnTriggerHeadThrow;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="InGameControlActions.UnregisterCallbacks(IInGameControlActions)" />.
        /// </summary>
        /// <seealso cref="InGameControlActions.UnregisterCallbacks(IInGameControlActions)" />
        public void RemoveCallbacks(IInGameControlActions instance)
        {
            if (m_Wrapper.m_InGameControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="InGameControlActions.AddCallbacks(IInGameControlActions)" />
        /// <seealso cref="InGameControlActions.RemoveCallbacks(IInGameControlActions)" />
        /// <seealso cref="InGameControlActions.UnregisterCallbacks(IInGameControlActions)" />
        public void SetCallbacks(IInGameControlActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="InGameControlActions" /> instance referencing this action map.
    /// </summary>
    public InGameControlActions @inGameControl => new InGameControlActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "inGameControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="InGameControlActions.AddCallbacks(IInGameControlActions)" />
    /// <seealso cref="InGameControlActions.RemoveCallbacks(IInGameControlActions)" />
    public interface IInGameControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "stickMovement" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStickMovement(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TriggerHeadThrowAim" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTriggerHeadThrowAim(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TriggerRebuild" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTriggerRebuild(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "aimHead" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAimHead(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "jump/cling" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJumpcling(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TriggerHeadThrow" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTriggerHeadThrow(InputAction.CallbackContext context);
    }
}
