//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/controller input system/playerControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""playerControl"",
    ""maps"": [
        {
            ""name"": ""inGameControl"",
            ""id"": ""a7b7fb76-47fa-4561-a2a5-f1023351948c"",
            ""actions"": [
                {
                    ""name"": ""stickMovement"",
                    ""type"": ""Value"",
                    ""id"": ""b6ed247e-cb2d-4b0a-b20f-648dec7d3af2"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerHeadThrowAim"",
                    ""type"": ""Button"",
                    ""id"": ""9450f86f-f5ec-4d4a-88c7-47e4ec359ab1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerRebuild"",
                    ""type"": ""Button"",
                    ""id"": ""8cd5291b-35ae-4834-86b6-bc794d3eec4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""aimHead"",
                    ""type"": ""Value"",
                    ""id"": ""8c7c536a-5e77-4e9b-905a-5f61adc3f8d4"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""jump/cling"",
                    ""type"": ""Button"",
                    ""id"": ""89fea38b-2b29-4e62-8049-d0765679796d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerHeadThrow"",
                    ""type"": ""Button"",
                    ""id"": ""736b8ae8-a927-4a38-9abe-ed8af1889ff2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""52f35105-fe8a-4b38-8880-6bc13b9d7f89"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""stickMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4be54c7f-d7e5-4572-9089-24d485889161"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerHeadThrowAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31c617f8-9e9d-46fc-9991-54b9cadd73cb"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerRebuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46ee7940-39aa-46cd-b314-7d0491bf0231"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""aimHead"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da2fb662-db55-4706-b5fa-8b31ed3902e4"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump/cling"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9c3d6c2-1843-4af5-98dc-8e36513cbb33"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerHeadThrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // inGameControl
        m_inGameControl = asset.FindActionMap("inGameControl", throwIfNotFound: true);
        m_inGameControl_stickMovement = m_inGameControl.FindAction("stickMovement", throwIfNotFound: true);
        m_inGameControl_TriggerHeadThrowAim = m_inGameControl.FindAction("TriggerHeadThrowAim", throwIfNotFound: true);
        m_inGameControl_TriggerRebuild = m_inGameControl.FindAction("TriggerRebuild", throwIfNotFound: true);
        m_inGameControl_aimHead = m_inGameControl.FindAction("aimHead", throwIfNotFound: true);
        m_inGameControl_jumpcling = m_inGameControl.FindAction("jump/cling", throwIfNotFound: true);
        m_inGameControl_TriggerHeadThrow = m_inGameControl.FindAction("TriggerHeadThrow", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // inGameControl
    private readonly InputActionMap m_inGameControl;
    private List<IInGameControlActions> m_InGameControlActionsCallbackInterfaces = new List<IInGameControlActions>();
    private readonly InputAction m_inGameControl_stickMovement;
    private readonly InputAction m_inGameControl_TriggerHeadThrowAim;
    private readonly InputAction m_inGameControl_TriggerRebuild;
    private readonly InputAction m_inGameControl_aimHead;
    private readonly InputAction m_inGameControl_jumpcling;
    private readonly InputAction m_inGameControl_TriggerHeadThrow;
    public struct InGameControlActions
    {
        private @PlayerControl m_Wrapper;
        public InGameControlActions(@PlayerControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @stickMovement => m_Wrapper.m_inGameControl_stickMovement;
        public InputAction @TriggerHeadThrowAim => m_Wrapper.m_inGameControl_TriggerHeadThrowAim;
        public InputAction @TriggerRebuild => m_Wrapper.m_inGameControl_TriggerRebuild;
        public InputAction @aimHead => m_Wrapper.m_inGameControl_aimHead;
        public InputAction @jumpcling => m_Wrapper.m_inGameControl_jumpcling;
        public InputAction @TriggerHeadThrow => m_Wrapper.m_inGameControl_TriggerHeadThrow;
        public InputActionMap Get() { return m_Wrapper.m_inGameControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameControlActions set) { return set.Get(); }
        public void AddCallbacks(IInGameControlActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameControlActionsCallbackInterfaces.Add(instance);
            @stickMovement.started += instance.OnStickMovement;
            @stickMovement.performed += instance.OnStickMovement;
            @stickMovement.canceled += instance.OnStickMovement;
            @TriggerHeadThrowAim.started += instance.OnTriggerHeadThrowAim;
            @TriggerHeadThrowAim.performed += instance.OnTriggerHeadThrowAim;
            @TriggerHeadThrowAim.canceled += instance.OnTriggerHeadThrowAim;
            @TriggerRebuild.started += instance.OnTriggerRebuild;
            @TriggerRebuild.performed += instance.OnTriggerRebuild;
            @TriggerRebuild.canceled += instance.OnTriggerRebuild;
            @aimHead.started += instance.OnAimHead;
            @aimHead.performed += instance.OnAimHead;
            @aimHead.canceled += instance.OnAimHead;
            @jumpcling.started += instance.OnJumpcling;
            @jumpcling.performed += instance.OnJumpcling;
            @jumpcling.canceled += instance.OnJumpcling;
            @TriggerHeadThrow.started += instance.OnTriggerHeadThrow;
            @TriggerHeadThrow.performed += instance.OnTriggerHeadThrow;
            @TriggerHeadThrow.canceled += instance.OnTriggerHeadThrow;
        }

        private void UnregisterCallbacks(IInGameControlActions instance)
        {
            @stickMovement.started -= instance.OnStickMovement;
            @stickMovement.performed -= instance.OnStickMovement;
            @stickMovement.canceled -= instance.OnStickMovement;
            @TriggerHeadThrowAim.started -= instance.OnTriggerHeadThrowAim;
            @TriggerHeadThrowAim.performed -= instance.OnTriggerHeadThrowAim;
            @TriggerHeadThrowAim.canceled -= instance.OnTriggerHeadThrowAim;
            @TriggerRebuild.started -= instance.OnTriggerRebuild;
            @TriggerRebuild.performed -= instance.OnTriggerRebuild;
            @TriggerRebuild.canceled -= instance.OnTriggerRebuild;
            @aimHead.started -= instance.OnAimHead;
            @aimHead.performed -= instance.OnAimHead;
            @aimHead.canceled -= instance.OnAimHead;
            @jumpcling.started -= instance.OnJumpcling;
            @jumpcling.performed -= instance.OnJumpcling;
            @jumpcling.canceled -= instance.OnJumpcling;
            @TriggerHeadThrow.started -= instance.OnTriggerHeadThrow;
            @TriggerHeadThrow.performed -= instance.OnTriggerHeadThrow;
            @TriggerHeadThrow.canceled -= instance.OnTriggerHeadThrow;
        }

        public void RemoveCallbacks(IInGameControlActions instance)
        {
            if (m_Wrapper.m_InGameControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameControlActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameControlActions @inGameControl => new InGameControlActions(this);
    public interface IInGameControlActions
    {
        void OnStickMovement(InputAction.CallbackContext context);
        void OnTriggerHeadThrowAim(InputAction.CallbackContext context);
        void OnTriggerRebuild(InputAction.CallbackContext context);
        void OnAimHead(InputAction.CallbackContext context);
        void OnJumpcling(InputAction.CallbackContext context);
        void OnTriggerHeadThrow(InputAction.CallbackContext context);
    }
}
